#!/usr/bin/env python3
# Copyright (c) 2026 Bruno Vunderl
#
# SPDX-License-Identifier: GPL-3.0-or-later
"""
Turn fonts/3x5MatrixDisplay.ttf into src/font3x5.c.

The font is a pixel font: every glyph is drawn on a 3x5 grid of 64-unit squares
(1024 units per em, 16 pixels per em). Each pixel is read by testing whether the
centre of its square lies inside the glyph outline, so the result is exact. Glyphs
are stored as 15-bit masks: bit (row * 3 + col) is set for a lit pixel, row 0 on top.

Requires fontTools (pip install fonttools).
Usage:  python3 tools/gen_font.py
"""

import os
import sys

from fontTools.pens.pointInsidePen import PointInsidePen
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, "fonts", "3x5MatrixDisplay.ttf")
FIRST, LAST = 0x20, 0x7E
COLS, ROWS, UNIT = 3, 5, 64


def rasterise(font):
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    masks = []
    for code in range(FIRST, LAST + 1):
        glyph = glyph_set[cmap[code]]
        mask = 0
        for row in range(ROWS):
            for col in range(COLS):
                x = col * UNIT + UNIT // 2
                y = (ROWS - 1 - row) * UNIT + UNIT // 2  # font y grows upwards
                pen = PointInsidePen(glyph_set, (x, y))
                glyph.draw(pen)
                if pen.getResult():
                    mask |= 1 << (row * COLS + col)
        masks.append(mask)
    return masks


def art(mask):
    return ["".join("#" if mask >> (r * COLS + c) & 1 else "." for c in range(COLS))
            for r in range(ROWS)]


def main():
    masks = rasterise(TTFont(FONT))
    lines = [
        "/*",
        " * Copyright (c) 2026 Bruno Vunderl",
        " *",
        " * SPDX-License-Identifier: GPL-3.0-or-later",
        " */",
        "",
        "/* Generated by tools/gen_font.py from fonts/3x5MatrixDisplay.ttf, do not edit. */",
        "",
        '#include "font3x5.h"',
        "",
        "/* Bit (row * 3 + col) is a lit pixel, row 0 on top. First glyph is ' ' (0x20). */",
        "const uint16_t font3x5[FONT3X5_GLYPHS] = {",
    ]
    for i, mask in enumerate(masks):
        code = FIRST + i
        label = chr(code) if chr(code) not in "\\/*" else f"0x{code:02x}"
        lines.append(f"\t0x{mask:04x}, /* {label} */")
    lines.append("};")
    with open(os.path.join(ROOT, "src", "font3x5.c"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote src/font3x5.c ({len(masks)} glyphs)")

    if "--show" in sys.argv:
        for ch in sys.argv[sys.argv.index("--show") + 1]:
            print(ch)
            print("\n".join("  " + r for r in art(masks[ord(ch) - FIRST])))


if __name__ == "__main__":
    main()
