/*
 * Copyright (c) 2026 Bruno Vunderl
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/* Generated by tools/pixel_logos.py, do not edit. */

#ifndef TC001_LOGOS_H_
#define TC001_LOGOS_H_

#include <stdint.h>

#define LOGO_SIZE 8

/*
 * 8x8 pixel-art logos as RGB888, row by row, so they can be passed straight to
 * display_write() with a 8x8 buffer descriptor.
 */
extern const uint8_t logo_rust[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_csharp[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_crate[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_nuget[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_wx_sun[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_wx_moon[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_wx_partly[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_wx_cloud[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_wx_fog[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_wx_rain[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_wx_snow[LOGO_SIZE * LOGO_SIZE * 3];
extern const uint8_t logo_wx_storm[LOGO_SIZE * LOGO_SIZE * 3];

#endif /* TC001_LOGOS_H_ */
